services:
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile
    image: bapeda-profile:staging
    container_name: bapeda-profile-staging
    restart: unless-stopped
    ports:
      - "3032:3000"
    env_file:
      - .env.staging
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  staging-network:
    name: staging-network
    driver: bridge
